#latitude: 30.0
#longitude: 30.0
units: "metric"
api-key: 47f3a51cb6673fd52bb569912fbcb199
#url: "https://api.openweathermap.org/data/2.5/weather"

#url: "https://api.openweathermap.org/data/2.5/weather?lat=${latitude}&lon=${longitude}&appid=${api-key}"

spring:
  cloud:
    openfeign:
      client:
        config:
          weather:
            url: "https://api.openweathermap.org/data/2.5/weather?units=${units}&appid=${api-key}"
            connect-timeout: 5000
            read-timeout: 5000
resilience4j:
  retry:
    instances:
      weather-retry:
        max-attempts: 3
        wait-duration: 3s
        retry-exceptions:
          - feign.FeignException.BadGateway
          - feign.FeignException.BadRequest
          - feign.FeignException.NotFound

  circuitbreaker:
    instances:
      weather-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2

